CREATE TABLE bank_loan_data(
    id INT PRIMARY KEY NOT NULL,
    address_state VARCHAR(50) NOT NULL,
    application_type VARCHAR(50) NOT NULL,
    emp_length VARCHAR(50) NOT NULL,
    emp_title VARCHAR(100),
    grade VARCHAR(50) NOT NULL,
    home_ownership VARCHAR(50) NOT NULL,
    issue_date DATE NOT NULL,
    last_credit_pull_date DATE NOT NULL,
    last_payment_date DATE NOT NULL,
    loan_status VARCHAR(50) NOT NULL,
    next_payment_date DATE NOT NULL,
    member_id INT NOT NULL,
    purpose VARCHAR(50) NOT NULL,
    sub_grade VARCHAR(50) NOT NULL,
    term VARCHAR(50) NOT NULL,
    verification_status VARCHAR(50) NOT NULL,
    annual_income FLOAT NOT NULL,
    dti FLOAT NOT NULL,
    installment FLOAT NOT NULL,
    int_rate FLOAT NOT NULL,
    loan_ammount INT NOT NULL,
    total_acc INT NOT NULL,
    total_payment INT NOT NULL
)